---
apiVersion: example.crossplane.io/v1beta1
kind: XR
metadata:
  labels:
    a: b
  name: example
spec:
  count: 2
  id: abc
  maxReplicas: 3
status:
  dummy: cool-status
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: AccessKey
metadata:
  annotations:
    crossplane.io/composition-resource-name: sample-access-key-0
  generateName: example-
  labels:
    crossplane.io/composite: example
  ownerReferences:
  - apiVersion: example.crossplane.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: XR
    name: example
    uid: ""
spec:
  forProvider:
    userSelector:
      matchLabels:
        testing.upbound.io/example-name: test-user-0
  writeConnectionSecretToRef:
    name: sample-access-key-secret-0
    namespace: crossplane-system
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: AccessKey
metadata:
  annotations:
    crossplane.io/composition-resource-name: sample-access-key-1
  generateName: example-
  labels:
    crossplane.io/composite: example
  ownerReferences:
  - apiVersion: example.crossplane.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: XR
    name: example
    uid: ""
spec:
  forProvider:
    userSelector:
      matchLabels:
        testing.upbound.io/example-name: test-user-1
  writeConnectionSecretToRef:
    name: sample-access-key-secret-1
    namespace: crossplane-system
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    crossplane.io/composition-resource-name: test-user-0
  generateName: example-
  labels:
    crossplane.io/composite: example
    dummy: bar
    testing.upbound.io/example-name: test-user-0
  ownerReferences:
  - apiVersion: example.crossplane.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: XR
    name: example
    uid: ""
spec:
  forProvider: {}
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    crossplane.io/composition-resource-name: test-user-1
  generateName: example-
  labels:
    crossplane.io/composite: example
    dummy: bar
    testing.upbound.io/example-name: test-user-1
  ownerReferences:
  - apiVersion: example.crossplane.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: XR
    name: example
    uid: ""
spec:
  forProvider: {}
