# Partner Team vCluster Configuration
# Restricted environment with pre-populated resources

# Moderate resource quotas
policies:
  resourceQuota:
    enabled: true
    quota:
      requests.cpu: "2"
      requests.memory: "4Gi"
      limits.cpu: "4"
      limits.memory: "8Gi"
      persistentvolumeclaims: "5"
      services.nodeports: "0"
      services.loadbalancers: "0"

  limitRange:
    enabled: true
    default:
      cpu: "100m"
      memory: "128Mi"
    defaultRequest:
      cpu: "50m"
      memory: "64Mi"

# Limited sync - only essential resources
sync:
  toHost:
    pods:
      enabled: true
      # Add node selector to restrict scheduling
      translate:
        - kind: Pod
          apiVersion: v1
          patches:
            - op: add
              path: spec.nodeSelector
              value:
                team: "shared"  # Only schedule on shared nodes
  fromHost:
    nodes:
      enabled: true
      selector:
        labelSelector: "team=shared"  # Only see shared nodes

# Pre-populate resources
experimental:
  deploy:
    manifests: |-
      ---
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: platform-config
        namespace: default
      data:
        api_endpoint: "https://api.platform.example.com"
        environment: "partner"
        region: "us-west-2"
      ---
      apiVersion: v1
      kind: Secret
      metadata:
        name: platform-credentials
        namespace: default
      type: Opaque
      stringData:
        token: "dummy-platform-token-for-demo"
        client_id: "partner-client-12345"
      ---
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: partner-guidelines
        namespace: default
      data:
        usage_policy: |
          Partner Platform Usage Guidelines:
          1. All workloads must be tagged with partner ID
          2. Resource limits are enforced automatically
          3. No access to host cluster resources
          4. Data must remain within the virtual cluster
          5. Support available via platform portal

# Control plane configuration
controlPlane:
  distro:
    k3s:
      enabled: true
      image:
        tag: "v1.29.0-k3s1"
  backingStore:
    database:
      embedded:
        enabled: true

# Restricted networking
networking:
  replicateServices:
    toHost: []  # No service replication to host

# Security policies
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# Disable advanced features
storage:
  persistence:
    size: "2Gi"  # Limited storage

# Monitoring disabled for partners
monitoring:
  serviceMonitor:
    enabled: false

# Disable pro features
pro: false