apiVersion: acmeplatform.com/v1alpha1
kind: AppClaim
metadata:
  name: platform-demo 
  labels:
    app-owner: piotrzan
spec:
  id: acmeplatform
  compositionSelector:
    matchLabels:
      type: frontend
  parameters:
    namespace: devops-team
    image: piotrzan/nginx-demo:green
    host: acmeplatform.127.0.0.1.nip.io
